[dev]
  command = "yarn start"
  targetPort = 8000
  port = 9999
  publish = "public"
  functionsPort = 7000

[[headers]]
  for = "/*"
  [headers.values]
  cache-control = '''
  max-age=0,
  no-cache,
  no-store,
  must-revalidate'''