enabled: false
section_title: About Me 2
display_name: Alchie Tagudin
title: Frontend Web Developer
photo: /uploads/tagudin.jpg
cv_link: 
description: I’m Alchie Tagudin a marketing specialist with over five years work
  experience. Donec sed fringilla lectus, non vulputate orci. Integer id libero
  euismod, interdum ligula vel, porttitor magna. Sed euismod maximus finibus.
  Pellentesque tempus ultricies nisi at cursus. Nulla at nisi tellus.
  Suspendisse potenti.
education:
  - course: BS Accountancy
    school: Ateneo de Davao University
    started: "2002"
    graduated: "2007"
awards:
  - title: none
    sponsor: none
    year: none
links:
  - name: Facebook
    url: "#facebook"
  - name: Twitter
    url: "#twitter"
experiences:
  - position: Frontend Web Developer
    company: PetLab Co.
    started: June 2020
    ended: June 2020
    duration: none
    description: none
skills:
  - title: Social Media
    sponsor: Social Media
    year: Social Media
    valuenow: "85"
    valuemin: "0"
    valuemax: "100"
  - valuenow: "55"
    valuemin: "0"
    valuemax: "100"
    title: Project Management
  - valuenow: "70"
    valuemin: "0"
    valuemax: "100"
    title: Analytical Knowledge
  - valuenow: "90"
    valuemin: "0"
    valuemax: "100"
    title: Creativity & Expression
categories:
  - key: web
    title: Web
  - key: brand
    title: Brand
  - key: design
    title: Design
portfolios:
  - category: web
    title: Ants Design Studio
    url: https://www.antsdesignsstudio.com/
    photo: /uploads/antsdesignsstudio.png