backend:
  name: git-gateway
  branch: new-content # Branch to update (optional; defaults to master)

local_backend: true
publish_mode: editorial_workflow
media_folder: static/uploads
public_folder: /uploads

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
  
collections:
  - label: "Page Sections"
    name: "page-sections"
    files:
      - label: "Page Cover"
        name: "page-sections-cover"
        file: "content/page-sections-cover.yml"
        fields:
          - {label: Display Name, name: display_name, widget: string}
          - {label: Title, name: title, widget: string}
          - {label: Photo, name: photo, widget: image}

      - label: "About Me"
        name: "page-sections-about"
        file: "content/page-sections-about.yml"
        fields:
          - {label: Section Title, name: section_title, widget: string}
          - {label: Display Name, name: display_name, widget: string}
          - {label: Title, name: title, widget: string}
          - {label: Photo, name: photo, widget: image}
          - {label: Description, name: description, widget: markdown}
          - label: Education
            name: education
            widget: list
            fields:
              - {label: Course, name: course, widget: string}
              - {label: School, name: school, widget: string}
              - {label: Started, name: started, widget: string}
              - {label: Graduated, name: graduated, widget: string, required: false}
          - label: Awards
            name: awards
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Sponsor, name: sponsor, widget: string}
              - {label: Year, name: year, widget: string}

      - label: "Skills"
        name: "page-sections-skills"
        file: "content/page-sections-skills.yml"
        fields:
          - {label: Section Title, name: section_title, widget: string}
          - {label: Description, name: description, widget: string}
          - label: Skills
            name: skills
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: valuenow, name: valuenow, widget: string, default: "0"}
              - {label: valuemin, name: valuemin, widget: string, default: "0"}
              - {label: valuemax, name: valuemax, widget: string, default: "100"}

      - label: "Experiences"
        name: "page-sections-experiences"
        file: "content/page-sections-experiences.yml"
        fields:
          - {label: Section Title, name: section_title, widget: string}
          - {label: Description, name: description, widget: string}
          - label: Experiences
            name: experiences
            widget: list
            fields:
              - {label: Position, name: position, widget: string}
              - {label: Company, name: company, widget: string}
              - {label: Started, name: started, widget: string}
              - {label: Ended, name: ended, widget: string, required: false}
              - {label: Duration, name: duration, widget: string, required: false}
              - {label: Description, name: description, widget: markdown, required: false}
              
      - label: "Services"
        name: "page-sections-services"
        file: "content/page-sections-services.yml"
        fields:
          - {label: Section Title, name: section_title, widget: string}
          - {label: Description, name: description, widget: string}
          - label: Services
            name: services
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: string}
              - {label: Icon, name: icon, widget: string}
              
      - label: "Portfolio"
        name: "page-sections-portfolio"
        file: "content/page-sections-portfolio.yml"
        fields:
          - {label: Section Title, name: section_title, widget: string}
          - {label: Description, name: description, widget: string}
          - label: Categories
            name: categories
            widget: list
            fields:
              - {label: Key, name: key, widget: string}
              - {label: Title, name: title, widget: string}

      - label: "Testimonials"
        name: "page-sections-testimonials"
        file: "content/page-sections-testimonials.yml"
        fields:
          - {label: Section Title, name: section_title, widget: string}
          - {label: Description, name: description, widget: string}

      - label: "Contacts"
        name: "page-sections-contacts"
        file: "content/page-sections-contacts.yml"
        fields:
          - {label: Section Title, name: section_title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Phone Number, name: phone_number, widget: string}
          - {label: Address, name: address, widget: string}
          - {label: Email Address, name: email_address, widget: string}

  - label: "Settings"
    name: "settings"
    files:
      - label: "Social Media"
        name: "social-media"
        file: "content/social-media-accounts.yml"
        fields:
          - label: Links
            name: links
            widget: list
            fields:
              - {label: Site Name, name: name, widget: string}
              - {label: URL, name: url, widget: string}
