backend:
  name: git-gateway
  branch: new-content # Branch to update (optional; defaults to master)

local_backend: true
publish_mode: simple
media_folder: static/uploads
public_folder: /uploads

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
  
collections:

  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{title}}'
    fields:
      - { label: 'Publish Date', name: 'publish_date', widget: 'datetime' }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image', choose_url: true, required: true }
      - { label: 'Tags', name: 'tags', widget: 'list', allow_add: true, default: ["article"] }
      - label: "Category"
        name: "category"
        widget: "relation"
        collection: "settings"
        search_fields: ["categories.*.name"]
        display_fields: ["categories.*.name"]
        value_field: "categories.*.name"

  - label: "Page Sections"
    name: "page-sections"
    files:
      - label: "Page Cover"
        name: "page-sections-cover"
        file: "content/page-sections-cover.yml"
        fields:
          - {label: Enabled, name: enabled, widget: boolean, default: true}
          - {label: Display Name, name: display_name, widget: string}
          - {label: Title, name: title, widget: string}
          - {label: Photo, name: photo, widget: image}
          - {label: Background Image, name: background_image, widget: image}

      - label: "About Me"
        name: "page-sections-about"
        file: "content/page-sections-about.yml"
        fields:
          - {label: Enabled, name: enabled, widget: boolean, default: true}
          - {label: Section Title, name: section_title, widget: string}
          - {label: Display Name, name: display_name, widget: string}
          - {label: Title, name: title, widget: string}
          - {label: Download CV Link, name: cv_link, widget: string, required: false}
          - {label: Photo, name: photo, widget: image}
          - {label: Description, name: description, widget: markdown}
          - label: Education
            name: education
            widget: list
            fields:
              - {label: Course, name: course, widget: string}
              - {label: School, name: school, widget: string}
              - {label: Started, name: started, widget: string}
              - {label: Graduated, name: graduated, widget: string, required: false}
          - label: Awards
            label_singular: Award
            name: awards
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Sponsor, name: sponsor, widget: string}
              - {label: Year, name: year, widget: string}

      - label: "Skills"
        name: "page-sections-skills"
        file: "content/page-sections-skills.yml"
        fields:
          - {label: Enabled, name: enabled, widget: boolean, default: true}
          - {label: Section Title, name: section_title, widget: string}
          - {label: Description, name: description, widget: string}
          - label: Skills
            label_singular: Skill
            name: skills
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: valuenow, name: valuenow, widget: string, default: "0"}
              - {label: valuemin, name: valuemin, widget: string, default: "0"}
              - {label: valuemax, name: valuemax, widget: string, default: "100"}

      - label: "Experiences"
        name: "page-sections-experiences"
        file: "content/page-sections-experiences.yml"
        fields:
          - {label: Enabled, name: enabled, widget: boolean, default: true}
          - {label: Section Title, name: section_title, widget: string}
          - {label: Description, name: description, widget: string}
          - label: Experiences
            label_singular: Experience
            name: experiences
            widget: list
            fields:
              - {label: Position, name: position, widget: string}
              - {label: Company, name: company, widget: string}
              - {label: Started, name: started, widget: string}
              - {label: Ended, name: ended, widget: string, required: false}
              - {label: Duration, name: duration, widget: string, required: false}
              - {label: Description, name: description, widget: markdown, required: false}
              
      - label: "Services"
        name: "page-sections-services"
        file: "content/page-sections-services.yml"
        fields:
          - {label: Enabled, name: enabled, widget: boolean, default: true}
          - {label: Section Title, name: section_title, widget: string}
          - {label: Description, name: description, widget: string}
          - label: Services
            label_singular: Service
            name: services
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: string}
              - {label: Icon, name: icon, widget: string}
              
      - label: "Portfolio"
        name: "page-sections-portfolio"
        file: "content/page-sections-portfolio.yml"
        fields:
          - {label: Enabled, name: enabled, widget: boolean, default: true}
          - {label: Section Title, name: section_title, widget: string}
          - {label: Description, name: description, widget: string}
          - label: Categories
            label_singular: Category
            name: categories
            widget: list
            fields:
              - {label: Key, name: key, widget: string}
              - {label: Title, name: title, widget: string}
          - label: Portfolios
            label_singular: Portfolio
            name: portfolios
            widget: list
            fields:
              - label: "Category"
                name: "category"
                widget: "relation"
                collection: "page-sections"
                search_fields: ["categories.*.key", "categories.*.title"]
                display_fields: ["categories.*.key", "categories.*.title"]
                value_field: "categories.*.key"
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: string}
              - {label: URL, name: url, widget: string}
              - {label: Photo, name: photo, widget: image}

      - label: "Testimonials"
        name: "page-sections-testimonials"
        file: "content/page-sections-testimonials.yml"
        fields:
          - {label: Enabled, name: enabled, widget: boolean, default: true}
          - {label: Section Title, name: section_title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Background Image, name: background_image, widget: image}
          - label: Testimonials
            label_singular: Testimonial
            name: testimonials
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Company, name: company, widget: string}
              - {label: Quote, name: quote, widget: string}
              - {label: Photo, name: photo, widget: image}

      - label: "Blog"
        name: "page-sections-blog"
        file: "content/page-sections-blog.yml"
        fields:
          - {label: Enabled, name: enabled, widget: boolean, default: true}
          - {label: Section Title, name: section_title, widget: string}
          - {label: Description, name: description, widget: string}

      - label: "Contacts"
        name: "page-sections-contacts"
        file: "content/page-sections-contacts.yml"
        fields:
          - {label: Enabled, name: enabled, widget: boolean, default: true}
          - {label: Section Title, name: section_title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Phone Number, name: phone_number, widget: string}
          - {label: Address, name: address, widget: string}
          - {label: Email Address, name: email_address, widget: string}

  - label: "Settings"
    name: "settings"
    files:
      - label: "Site Navigation"
        name: "site-navigation"
        file: "content/settings-site-navigation.yml"
        fields:
          - label: Navigation
            name: navigation
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: URL, name: url, widget: string}

      - label: "Blog Categories"
        name: "blog-categories"
        file: "content/settings-blog-categories.yml"
        fields:
          - label: Categories
            name: categories
            widget: list
            fields:
              - {label: Name, name: name, widget: string}

      - label: "Social Media"
        name: "social-media"
        file: "content/settings-social-media.yml"
        fields:
          - {label: Facebook, name: facebook_url, widget: string,required: false}
          - {label: Github, name: github_url, widget: string,required: false}
          - {label: LinkedIn, name: linkedin_url, widget: string,required: false}
          - label: Others
            name: others
            widget: list
            required: false
            fields:
              - {label: Name, name: name, widget: string}
              - {label: URL, name: url, widget: string}
              - {label: Icon, name: icon, widget: string}

    
